create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  date text not null,
  price integer not null,
  max_capacity integer,
  location text not null default '',
  description text not null default '',
  image_url text not null default '',
  host_user_id uuid,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  stripe_session_id text not null unique,
  buyer_user_id uuid,
  customer_email text,
  quantity integer not null,
  total_amount integer not null,
  payment_status text not null default 'pending',
  ticket_code text not null default '',
  checked_in boolean not null default false,
  checked_in_at timestamptz,
  cancelled_at timestamptz,
  email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.waitlist_entries (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  user_id uuid,
  email text not null,
  name text not null default '',
  notified_at timestamptz,
  converted_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.purchases add column if not exists buyer_user_id uuid;
alter table public.purchases add column if not exists ticket_code text not null default '';
alter table public.purchases add column if not exists checked_in boolean not null default false;
alter table public.purchases add column if not exists checked_in_at timestamptz;
alter table public.purchases add column if not exists cancelled_at timestamptz;
alter table public.purchases add column if not exists email_sent_at timestamptz;
alter table public.waitlist_entries add column if not exists user_id uuid;
alter table public.waitlist_entries add column if not exists email text not null default '';
alter table public.waitlist_entries add column if not exists name text not null default '';
alter table public.waitlist_entries add column if not exists notified_at timestamptz;
alter table public.waitlist_entries add column if not exists converted_at timestamptz;
alter table public.waitlist_entries add column if not exists cancelled_at timestamptz;

alter table public.events add column if not exists location text not null default '';
alter table public.events add column if not exists description text not null default '';
alter table public.events add column if not exists image_url text not null default '';
alter table public.events add column if not exists max_capacity integer;
alter table public.events add column if not exists host_user_id uuid;
alter table public.events add column if not exists is_published boolean not null default true;

alter table public.events enable row level security;
alter table public.purchases enable row level security;
alter table public.waitlist_entries enable row level security;

create unique index if not exists waitlist_entries_event_email_active_idx
on public.waitlist_entries (event_id, lower(email))
where cancelled_at is null and converted_at is null;

drop policy if exists "Anyone can read events" on public.events;
create policy "Anyone can read events"
on public.events
for select
to public
using (
  is_published = true
  or host_user_id = auth.uid()
);

drop policy if exists "Anyone can create events" on public.events;
drop policy if exists "Authenticated users can create events" on public.events;
create policy "Authenticated users can create events"
on public.events
for insert
to authenticated
with check (auth.uid() = host_user_id);

drop policy if exists "Authenticated users can update events" on public.events;
create policy "Authenticated users can update events"
on public.events
for update
to authenticated
using (auth.uid() = host_user_id)
with check (auth.uid() = host_user_id);

drop policy if exists "Authenticated users can delete events" on public.events;
create policy "Authenticated users can delete events"
on public.events
for delete
to authenticated
using (auth.uid() = host_user_id);

drop policy if exists "Anyone can create purchases" on public.purchases;
create policy "Anyone can create purchases"
on public.purchases
for insert
to public
with check (true);

drop policy if exists "Authenticated users can read purchases" on public.purchases;
create policy "Authenticated users can read purchases"
on public.purchases
for select
to authenticated
using (
  buyer_user_id = auth.uid()
  or (
    customer_email is not null
    and customer_email = auth.jwt() ->> 'email'
  )
  or exists (
    select 1
    from public.events
    where public.events.id = public.purchases.event_id
      and public.events.host_user_id = auth.uid()
  )
);

drop policy if exists "Hosts can update purchases for their events" on public.purchases;
create policy "Hosts can update purchases for their events"
on public.purchases
for update
to authenticated
using (
  exists (
    select 1
    from public.events
    where public.events.id = public.purchases.event_id
      and public.events.host_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.events
    where public.events.id = public.purchases.event_id
      and public.events.host_user_id = auth.uid()
  )
);

drop policy if exists "Anyone can join waitlist" on public.waitlist_entries;
create policy "Anyone can join waitlist"
on public.waitlist_entries
for insert
to public
with check (true);

drop policy if exists "Hosts can read waitlist entries" on public.waitlist_entries;
create policy "Hosts can read waitlist entries"
on public.waitlist_entries
for select
to authenticated
using (
  exists (
    select 1
    from public.events
    where public.events.id = public.waitlist_entries.event_id
      and public.events.host_user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('event-images', 'event-images', true)
on conflict (id) do update
set name = excluded.name, public = excluded.public;

drop policy if exists "Anyone can view event images" on storage.objects;
create policy "Anyone can view event images"
on storage.objects
for select
to public
using (bucket_id = 'event-images');

drop policy if exists "Anyone can upload event images" on storage.objects;
create policy "Anyone can upload event images"
on storage.objects
for insert
to public
with check (bucket_id = 'event-images');
